
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#Should the module only add recipes for materials with JAOPCA molten fluids.
	jaopcaOnly = true
	#The materials that should not have ingot/gem melting recipes added.
	materialToMoltenMaterialBlacklist = []
	#The materials that should not have storage block melting recipes added.
	storageBlockToMoltenMaterialBlacklist = []
	#The materials that should not have nugget melting recipes added.
	nuggetToMoltenMaterialBlacklist = []
	#The materials that should not have dust melting recipes added.
	dustToMoltenMaterialBlacklist = []
	#The materials that should not have plate melting recipes added.
	plateToMoltenMaterialBlacklist = []
	#The materials that should not have gear melting recipes added.
	gearToMoltenMaterialBlacklist = []
	#The materials that should not have coin melting recipes added.
	coinToMoltenMaterialBlacklist = []
	#The materials that should not have rod melting recipes added.
	rodToMoltenMaterialBlacklist = []
	#The materials that should not have sheetmetal melting recipes added.
	sheetmetalToMoltenMaterialBlacklist = []
	#The materials that should not have ingot/gem casting recipes added.
	toMaterialMaterialBlacklist = []
	#The materials that should not have storage block casting recipes added.
	toStorageBlockMaterialBlacklist = []
	#The materials that should not have nugget casting recipes added.
	toNuggetMaterialBlacklist = []
	#The materials that should not have plate casting recipes added.
	toPlateMaterialBlacklist = []
	#The materials that should not have gear casting recipes added.
	toGearMaterialBlacklist = []
	#The materials that should not have coin casting recipes added.
	toCoinMaterialBlacklist = []
	#The materials that should not have rod casting recipes added.
	toRodMaterialBlacklist = []

