
#
#Client-only settings - If you're looking for general settings, look inside your worlds serverconfig folder!
[client]
	#
	#Show item descriptions on Shift and controls on Ctrl.
	enableTooltips = true
	#
	#Display a tooltip when looking at overstressed components.
	enableOverstressedTooltip = true
	#
	#Log a stack-trace when rendering issues happen within a moving contraption.
	explainRenderErrors = false
	#
	#Range: 0.0 ~ 1.0
	fanParticleDensity = 0.5
	#
	#Show colourful debug information while the F3-Menu is open.
	enableRainbowDebug = true
	#
	#Offset the overlay from goggle- and hover- information by this many pixels on the X axis; Use /create overlay
	#Range: > -2147483648
	overlayOffsetX = 20
	#
	#Offset the overlay from goggle- and hover- information by this many pixels on the Y axis; Use /create overlay
	#Range: > -2147483648
	overlayOffsetY = 0

