
#####################################################################################
#Features with configurable properties are split into categories
#####################################################################################
[cyclic]

	#####################################################################################
	# Enchantment related configs
	#####################################################################################
	[cyclic.enchantment]
		#Set false to disable enchantment
		traveler = true
		#Set false to disable enchantment
		reach = true
		#Set false to disable enchantment
		beekeeper = true
		#Set false to disable enchantment
		experience_boost = true
		#Set false to disable enchantment
		ender = true
		#Set false to disable enchantment
		disarm = true
		#Set false to disable enchantment
		excavate = false
		#Set false to disable enchantment
		magnet = false
		#Set false to disable enchantment
		multishot = true
		#Set false to disable enchantment
		beheading = true
		#Set false to disable enchantment
		quickshot = true
		#Set false to disable enchantment
		venom = true
		#Set false to disable enchantment
		life_leech = false
		#Set false to disable enchantment
		curse = false
		#Set false to disable enchantment
		auto_smelt = false
		#Set false to disable enchantment
		growth = true
		#Set false to disable enchantment
		step = true
		#Beheading enchant add player skin head drop, add any mob id and any skin
		beheadingEntityMHF = []

	#####################################################################################
	# Block specific configs
	#####################################################################################
	[cyclic.blocks]

		#Uncrafter settings
		[cyclic.blocks.uncrafter]
			#When searching for a recipe, does it ignore all NBT values (such as enchantments, RepairCost, Damage, etc).  For example, if false it will not uncraft damaged or enchanted items
			nbt_ignored = true
			#Block these from being un-crafted
			ignore_list = ["minecraft:elytra", "minecraft:beacon", "minecraft:magma", "minecraft:tipped_arrow", "minecraft:cobweb", "minecraft:*_dye", "minecraft:stick", "minecraft:netherite_ingot", "cyclic:gem_*", "forge:bucketfilled", "progressiveautomation:*", "spectrite:spectrite_arrow", "spectrite:spectrite_arrow_special", "techreborn:uumatter", "projecte:*"]
			#Ticks used for each uncraft
			#Range: 1 ~ 9999
			ticks = 1

