
[villager]
	#If villagers should be able to be picked up by sneaking and right-clicking
	sneak_pick_up = false
	#The volume of every villager related sound in this mod
	#Range: 0.0 ~ 1.0
	volume = 1.0
	#The location of the cycle trades button
	#Allowed Values: TOP_LEFT, TOP_RIGHT, NONE
	cycle_trades_button_location = "TOP_LEFT"

