
#Barrel Configs
[barrel]
	#Number of buckets the barrel will hold (Default: 1)
	#Range: > 1
	barrelNumberOfBuckets = 1
	#The max temperature a barrel can accept; water is 300 (Default: 300)
	#Range: > 0
	woodBarrelMaxTemp = 300
	#How much fluid rain will fill per iteration (Default: 2)
	#Range: > 1
	rainFillAmount = 2

	#Mob Spawn Configs
	[barrel.mob_spawn]
		#Number of seconds to spawn mobs (Default: 10)
		#Range: > 1
		secondsToSpawnMobs = 10

	#Compost Configs
	[barrel.compost]
		#Number of seconds to spawn mobs (Default: 10)
		#Range: > 1
		secondsToCompost = 10
		#How much solids need to be in barrel before composting starts (Default: 1000)
		#Range: > 1
		maxSolidAmount = 1000

	#Fluid Transform Configs
	[barrel.fluid_transform]
		#Number of seconds to transform fluids (Default: 10)
		#Range: > 1
		secondsToTransformFluid = 10

#Crook Configs
[crook]
	#Maximum additional string that a crook will drop from infested leaves in addition to the minimum string count (Default: 3)
	#Range: > 0
	maxBonusStringCount = 3
	#Minimum string that a crook will drop from infested leaves (Default: 2)
	#Range: > 1
	minStringCount = 2
	#Number of times the crook will "break" a leaf block to get drops (Default: 3)
	#Range: > 1
	vanillaDropSimulateCount = 3

#Crucible Configs
[crucible]
	#Ticks between melting operations (Default: 20)
	#Range: > 1
	ticksBetweenMelts = 20
	#Number of buckets the crucible will hold (Default: 4)
	#Range: > 1
	crucibleNumberOfBuckets = 4

	#Wooden Crucible Configs
	[crucible.wood]
		#Heat rate the Wood Crucible will use regardless of heat source below (Default: 2)
		#Range: > 1
		woodHeatRate = 2

#Infested Leaves Configs
[infested_leaves]
	#Number of seconds to for leaves to become completely infested (Default: 10)
	#Range: > 1
	secondsToTransformLeaves = 10
	#Number of ticks between infested leave spread attempts (Default: 100)
	#Range: > 1
	ticksBetweenSpreadAttempt = 100
	#Percentage of the time that infested leaves will spread (Default: 0.3)
	#Range: 0.001 ~ 1.0
	spreadChance = 0.3

#Sieve Configs
[sieve]
	#Sieve will get results for all mesh tiers below the one in the sieve (Default: true)
	flattenSieveRecipes = true
	#Meshes will have durability and can break. (Default: false)
	enableMeshDurability = false
	#Defines the radius that a sieve will attempt to activate other sieves (Default: 2)
	#Range: 0 ~ 5
	sieveRange = 2

#Compatibility Configs
[compatibility]
	#Should Thermal Expansion ores be enabled? (Default: false)
	enableThermalExpansion = false
	#Should Mekanism ores be enabled? (Default: false)
	enableMekanism = false
	#Should Silent Mechanism ores be enabled? (Default: false)
	enableSilentMechanism = false
	#Should Immersive Engineering ores be enabled? (Default: false)
	enableImmersiveEngineering = false
	#Should Create ores be enabled? (Default: false)
	enableCreate = false

#Debug Configs
[debug]
	#Enable extra logging? (Default: false)
	enableDebugLogging = false

