#Max blocks you can mine at once
#Range: 1 ~ 32768
max_blocks = 64
#Hunger multiplied for each block mined with ultimine
#Range: 0.0 ~ 10000.0
exhaustion_per_block = 20.0
#Doesn't stop at different types of stones
merge_stone = true
#Tools that won't let you active ultimine when held
tool_blacklist = ["mininggadgets:mininggadget"]
#Required for some modpacks
#Range: -1 ~ 8
render_text_manually = -1

