
#Style settings for all mods using mcjtylib
[style]
	#Color: energy bar low energy level
	colorEnergyBarLowEnergy = "631111"
	#Color: slider knob background while hovering
	colorSliderKnobHoveringFiller = "858aa5"
	#Color: list selected gradient
	colorListSelectedGradient1 = "616161"
	#Color: slider knob top left border
	colorSliderKnobTopLeft = "eeeeee"
	#Color: list selected gradient
	colorListSelectedGradient2 = "414141"
	#Color: list separator line
	colorListSeparatorLine = "5c5c5c"
	#Color: slider background
	colorSliderFiller = "636363"
	#Color: slider knob bottom right border while hovering
	colorSliderKnobHoveringBottomRight = "777c99"
	#Color: button bottom right border
	colorButtonBorderBottomRight = "777777"
	#Color: toggle button disabled top left border
	colorToggleDisabledBorderTopLeft = "eeeeee"
	#Color: energy bar top left border
	colorEnergyBarTopLeft = "2b2b2b"
	#Color: toggle button normal background
	colorToggleNormalFiller = "c6c6c6"
	#Color: slider knob top left border while dragging
	colorSliderKnobDraggingTopLeft = "5c669d"
	#Color: disabled button bottom right border
	colorButtonDisabledBorderBottomRight = "777777"
	#Color: toggle button normal bottom right border
	colorToggleNormalBorderBottomRight = "777777"
	#Color: energy bar spacer (between every energy level bar)
	colorEnergyBarSpacer = "430000"
	#Color: textfield backbground while focused
	colorTextFieldFocusedFiller = "eeeeee"
	#Color: list background
	colorListBackground = "8b8b8b"
	#Color: toggle button disabled bottom right border
	colorToggleDisabledBorderBottomRight = "777777"
	#Color: hovering button top left border
	colorButtonHoveringBorderTopLeft = "a5aac5"
	#Color: slider knob bottom right border while dragging
	colorSliderKnobDraggingBottomRight = "bcc5ff"
	#Color: slider knob bottom right border
	colorSliderKnobBottomRight = "333333"
	#Color: standard background color
	colorBackgroundFiller = "c6c6c6"
	#Color: textfield background
	colorTextFieldFiller = "c6c6c6"
	#Color: list selected and highlighted gradient
	colorListSelectedHighlightedGradient2 = "999900"
	#Color: list selected and highlighted gradient
	colorListSelectedHighlightedGradient1 = "bbbb00"
	#Color: text disabled
	colorTextDisabled = "a0a0a0"
	#Color: selected button background
	colorButtonSelectedFiller = "7f89bf"
	#Color: cycle button disabled small triangle
	colorCycleButtonTriangleDisabled = "888888"
	#Color: textfield cursor
	colorTextFieldCursor = "0"
	#Color: standard bevel bright border color
	colorBackgroundBevelBright = "ffffff"
	#Color: text normal
	colorTextNormal = "303030"
	#Color: textfield top left border
	colorTextFieldTopLeft = "2b2b2b"
	#Color: disabled button background
	colorButtonDisabledFiller = "c6c6c6"
	#Color: selected button background gradient
	colorButtonSelectedFillerGradient2 = "949ed4"
	#Color: toggle button normal top left border
	colorToggleNormalBorderTopLeft = "eeeeee"
	#Color: cycle button small triangle
	colorCycleButtonTriangleNormal = "0"
	#Color: selected button background gradient
	colorButtonSelectedFillerGradient1 = "6a74aa"
	#Color: energy bar text
	colorEnergyBarText = "ffffff"
	#Color: toggle button disabled background
	colorToggleDisabledFiller = "c6c6c6"
	#Color: button background gradient
	colorButtonFillerGradient1 = "b1b1b1"
	#Color: button background gradient
	colorButtonFillerGradient2 = "e1e1e1"
	#Color: slider knob background while dragging
	colorSliderKnobDraggingFiller = "7f89bf"
	#Color: slider top left border
	colorSliderTopLeft = "2b2b2b"
	#Color: selected button top left border
	colorButtonSelectedBorderTopLeft = "5c669d"
	#Color: standard bevel dark border color
	colorBackgroundBevelDark = "2b2b2b"
	#Color: energy bar high energy level
	colorEnergyBarHighEnergy = "dd0000"
	#Color: external border around buttons and some other components
	colorButtonExternalBorder = "0"
	#Color: energy bar bottom right border
	colorEnergyBarBottomRight = "ffffff"
	#Color: button background
	colorButtonFiller = "c6c6c6"
	#Color: slider knob top left border while hovering
	colorSliderKnobHoveringTopLeft = "a5aac5"
	#Color: textfield bottom right border
	colorTextFieldBottomRight = "ffffff"
	#Color: disabled button background gradient
	colorButtonDisabledFillerGradient1 = "b1b1b1"
	#Color: button top left border
	colorButtonBorderTopLeft = "eeeeee"
	#Color: disabled button background gradient
	colorButtonDisabledFillerGradient2 = "e1e1e1"
	#Color: selected button bottom right border
	colorButtonSelectedBorderBottomRight = "bcc5ff"
	#Color: slider knob background
	colorSliderKnobFiller = "8b8b8b"
	#Color: list highlighted gradient
	colorListHighlightedGradient1 = "717120"
	#Color: hovering button background gradient
	colorButtonHoveringFillerGradient1 = "8d92ad"
	#Color: hovering button background gradient
	colorButtonHoveringFillerGradient2 = "babfda"
	#Color: toggle button disabled text
	colorToggleTextDisabled = "a0a0a0"
	#Color: textfield backbground while hovering
	colorTextFieldHoveringFiller = "dadada"
	#Color: text as used in lists
	colorTextInListNormal = "151515"
	#Color: list highlighted gradient
	colorListHighlightedGradient2 = "515110"
	#Color: toggle button normal text
	colorToggleTextNormal = "303030"
	#Color: disabled button top left border
	colorButtonDisabledBorderTopLeft = "eeeeee"
	#Color: slider knob little marker lines
	colorSliderKnobMarkerLine = "4e4e4e"
	#Color: hovering button background
	colorButtonHoveringFiller = "a2a7c2"
	#Color: slider bottom right border
	colorSliderBottomRight = "ffffff"
	#Color: hovering button bottom right border
	colorButtonHoveringBorderBottomRight = "999ebb"

