
#Options related to player's death
[player_death]
	#Experience loss on death (%) [0..100|default:0]
	#Range: 0 ~ 100
	xp_loss = 0
	#Whether to handle player experience [false/true|default:true]
	handle_player_xp = true
	#Allows players with bad alignment and the perk tomb raider to steal items on abandoned graves [false/true|default:false]
	allow_tomb_raiding = false
	#The time in minutes before a Grave's Key isn't required to open a grave (-1 = disabled) [-1..MAX|default:-1]
	#Range: > -1
	decay_time = -1

#Miscellaneous options
[general]
	#The duration of the Ghostly Shape effect in seconds [0..MAX|default:120]
	#Range: > 0
	ghostly_shape_duration = 120
	#Scroll duration [1200..120000|default:12000]
	#Range: 1200 ~ 120000
	scroll_duration = 12000
	#The chance that a player receives an already enchanted Grave's Key on death [-1..100|default:0|disabled:-1]
	#Range: -1 ~ 100
	chance_enchanted_grave_key = 0
	#Required level in Knowledge of Death to craft Familiar Receptacle [0..20|default:10]
	#Range: 0 ~ 20
	familiar_receptacle_required_level = 10

#Allows to customize or disable the enchantments
[enchantments]
	#Enables the enchantment Plague Bringer [false/true|default:true]
	enable_enchantment_plague_bringer = true
	#Max level for Plague Bringer [1..10|default:5]
	#Range: 1 ~ 10
	max_level_plague_bringer = 3
	#Enables the enchantment Shadow Step [false/true|default:true]
	enable_enchantment_shadow_step = true
	#Enables the enchantment Soulbound [false/true|default:true]
	enable_enchantment_soulbound = true
	#Max level for Magic Siphon [1..10|default:5]
	#Range: 1 ~ 10
	max_level_magic_siphon = 5
	#Allows Plague Bringer to combine with Magic Siphon [false/true|default:false]
	plague_bringer_combining_magic_siphon = false
	#Allows Magic Siphon at enchanting table [false/true|default:true]
	magic_siphon_enchanting_table = true
	#Shadow Step is only active while sneaking [false/true|default:false]
	nerf_shadow_step = false
	#Allows Plague Bringer at enchanting table [false/true|default:false]
	plague_bringer_enchanting_table = false
	#Enables the enchantment Magic Siphon [false/true|default:true]
	enable_enchantment_magic_siphon = true

#For settings related to decorative tombs and magic items
[decorative_grave]
	#Maximum uses of a tablet [1..20|default:10]
	#Range: 1 ~ 20
	tablet_max_use = 10
	#The cooldown in minutes to reset the perks with the ankh of Pray [0..60|default:20]
	#Range: 0 ~ 60
	cooldown_reset_perk = 20
	#The cooldown in hours to pray with the Ânkh [1..10|default:3]
	#Range: 1 ~ 10
	cooldown_to_pray = 3
	#Sets the decorative graves unbreakable [false/true|default:false]
	unbreakable_decorative_grave = false

#Allows to disable some magic items
[allowedMagicItems]
	#Book of Disenchantment [false/true|default:true]
	allow_book_of_disenchantment = true
	#Scroll of Lightning Resistance [false/true|default:true]
	allow_scroll_of_lightning_resistance = true
	#Scroll of Feather Fall [false/true|default:true]
	allow_scroll_of_feather_fall = true
	#Voodoo Poppet [false/true|default:true]
	allow_voodoo_poppet = true
	#Scroll of Unstable Intangibleness [false/true|default:true]
	allow_scroll_of_unstable_intangibleness = true
	#Dust of Vanishing [false/true|default:true]
	allow_dust_of_vanishing = true
	#Tablet of Cupidity [false/true|default:true]
	allow_tablet_of_cupidity = true
	#Scroll of Purification [false/true|default:true]
	allow_scroll_of_purification = true
	#Scroll of Reach [false/true|default:true]
	allow_scroll_of_reach = true
	#Scroll of Preservation [false/true|default:true]
	allow_scroll_of_preservation = true
	#Tablet of Recall [false/true|default:true]
	allow_tablet_of_recall = true
	#Scroll of Knowledge [false/true|default:true]
	allow_scroll_of_knowledge = true
	#Tablet of Assistance [false/true|default:true]
	allow_tablet_of_assistance = true
	#Grave's Key [false/true|default:true]
	allow_grave_key = true
	#Scroll of True Sight [false/true|default:true]
	allow_scroll_of_true_sight = true
	#Lost Tablet [false/true|default:true]
	allow_lost_tablet = true
	#Tablet of Home [false/true|default:true]
	allow_tablet_of_home = true

#Allows to change the chance to drop some items
[loot]
	#Chance to loot a Lost Tablet by fishing [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_loot_lost_tablet = 100

