
#Options related to player's death
[player_death]
	#Whether to log the positions of players' graves [false/true|default:true]
	log_player_grave = true
	#Prevents death outside of world borders [false/true|default:false]
	prevent_death_outside_world = false
	#Allows player's graves to appear in water [false/true|default:true]
	allow_grave_in_water = true
	#The chance that creatures appear after the contents of a grave are retrieved [0..100|default:0]
	#Range: 0 ~ 100
	chance_mob_on_grave_recovery = 0
	#Whether to restore beneficial effects after a player dies [false/true|default:true]
	restore_effects_on_death = false
	#The chance that some items are lost on death [0..100|default:0]
	#Range: 0 ~ 100
	chance_loss_on_death = 0
	#Allows to fill an existing grave instead of creating a new one [false/true|default:true]
	allow_to_fill_existing_grave = true
	#The radius in which items should be collected when a grave is spawned [1..10|default:5]
	#Range: 1 ~ 10
	sniffer_range = 5
	#Whether to require a Grave's Key to access graves [false/true|default:true]
	player_grave_access = true
	#Graveless Areas
	no_grave_location = ["0, -300, 0, minecraft:overworld, 20"]
	#Knowledge of Death loss why dying [0..500|default:0]
	#Range: 0 ~ 500
	knowledge_loss = 0
	#Automatically equips any equipable items when respawning after a death [false/true|default:true]
	auto_equip_on_death_respawn = true
	#The percentage of items that are lost on death [0..100|default:0]
	#Range: 0 ~ 100
	percent_loss_on_death = 0
	#Whether graves should be allowed to bypass anti-griefing rules [false/true|default:true]
	graves_bypass_griefing_rules = true
	#Enables PvP mode, which allows players to open graves of players they kill [false/true|default:false]
	pvp_mode = false
	#Only stackable items can be lost on death [false/true|default:true]
	loss_on_death_only_for_stackable_items = true
	#Whether to handle player death [false/true|default:true]
	handle_player_death = true
	#Only abandoned graves can have losses of items (based on the decay_time) [false/true|default:true]
	loss_on_death_only_for_abandoned_grave = true

#Options related to player's alignment
[alignment]
	#Points for killing a villager (or minecolonies citizen) [0..50|default:-2]
	#Range: -50 ~ 0
	points_kill_villager = -2
	#Points for zombie villager exorcism [0..50|default:2]
	#Range: 0 ~ 50
	points_exorcism_zombie_villager = 2
	#Chance for tablet of cupidity [0..100|default:50]
	#Range: 0 ~ 100
	chance_tablet_of_cupidity = 50
	#Points for plundering a player's grave [-50..0|default:-2]
	#Range: -50 ~ 0
	points_plunder_player_grave = -2
	#Points for tablet of cupidity [-20..0|default:-1]
	#Range: -20 ~ 0
	points_tablet_of_cupidity = -1
	#Points for freeing a soul in a receptacle [0..50|default:3]
	#Range: 0 ~ 50
	points_free_soul_receptacle = 3
	#Points for killing a raider [0..20|default:1]
	#Range: 0 ~ 20
	points_kill_raider = 1
	#Chance for killing a raider [0..100|default:30]
	#Range: 0 ~ 100
	chance_kill_raider = 30
	#Points for Pray of Protection [0..50|default:2]
	#Range: 0 ~ 50
	points_pray_of_protection = 2

#Miscellaneous options
[general]
	#Allows teleportation to other dimensions [false/true|default:true]
	teleport_dim = true
	#Cooldown in minutes to use the command tbbind [-1..1440|default:-1]
	#Range: -1 ~ 1440
	cooldown_teleport_bind = -1
	#Beneficial effects that can't used by certain features such as ankh of pray, lollipop, scroll of preservation, alchemy perk and magic siphon enchantment
	unhandled_beneficial_effects = ["tombstone:ghostly_shape", "tombstone:preservation", "tombstone:exorcism"]
	#Harmful effects that can't used by certain features such as tablet of cupidity and the enchantment plague bringer
	unhandled_harmful_effects = ["minecraft:nausea"]
	#Fishing treasures can only be found in open water [false/true|default:true]
	fishing_treasure_in_open_water = true
	#Cooldown in minutes to use the command tbteleportdeath [-1..1440|default:-1]
	#Range: -1 ~ 1440
	cooldown_teleport_death = -1
	#Cooldown in minutes to use the command tbrequestteleport [-1..1440|default:-1]
	#Range: -1 ~ 1440
	cooldown_request_teleport = -1
	#The Halloween features also happen outside the dates of the event [false/true|default:false]
	persistant_halloween = false
	#Whether to cancel the Ghostly Shape effect on breaking a block or opening a chest [false/true|default:false]
	nerf_ghostly_shape = false
	#Increases the minimum time without sleeping for phantom spawn around player based on their level in Knowledge of Death [false/true|default:true]
	knowledge_reduce_phantom_spawn = true
	#Minimum time without sleeping for phantom to spawn around players [1200..MAX|default:72000]
	#Range: > 1200
	time_for_phantom_spawn = 72000
	#Allows players to be hurt by special damages related to some items [false/true|default:true]
	allow_beyond_the_grave_damage = true

#Allows to define the conditions for a village siege to begin
[village_siege]
	#Undeads always wear a helm when sieging [false/true|default:false]
	undead_wear_helm_in_siege = false
	#Shuffles the list of players before testing the siege location [false/true|default:true]
	shuffle_players_for_siege = true
	#Logs the different states of a village siege while searching for an adequate place [false/true|default:false]
	log_siege_state = false
	#Allows to use the positions of creative players to define the siege location [false/true|default:true]
	allow_creative_players_for_siege = true
	#Delay in seconds for a second test of siege when the first failed [0..1200|default:200]
	#Range: 0 ~ 1200
	delay_siege_test = 600
	#The creatures of the siege have a glowing effect (only uses this for test purposes) [false/true|default:false]
	glowing_creature_test = false
	#Allows to handle village sieges [false/true|default:true]
	handle_village_siege = true
	#Maximum of creatures appearing in a siege [0..100|default:20]
	#Range: 0 ~ 100
	siege_max_creature = 20
	#Chance for a siege to occur [0..100|default:10]
	#Range: 0 ~ 100
	siege_chance = 10
	#Mobs in siege are persistent [false/true|default:false]
	persistent_mob_in_siege = false

#For settings related to decorative tombs and magic items
[decorative_grave]
	#The creatures that can't be captured in receptacle
	black_list_capturable_souls = []
	#The structures that can't be discovered by lost tablets
	lost_tablet_denied_structures = []
	#Allows the purification effect to clear neutral effects [false/true|default:true]
	purification_affect_neutral_effects = true
	#Chance to receive a random beneficial spell effect when praying near a grave [0..100|default:40]
	#Range: 0 ~ 100
	chance_pray_reward = 40
	#Chance on 1000 that a soul appears on a grave [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_soul = 100
	#Duration of voodoo poppet's effects in seconds when preventing death [5..60000|default:60]
	#Range: 5 ~ 60000
	duration_voodoo_poppet_effects = 60
	#Time in minutes to check if a soul appears on a grave [10..10000|default:30]
	#Range: 10 ~ 10000
	time_soul = 30
	#Allows lost tablets to find locations outside the current world [false/true|default:true]
	lost_tablet_search_outside_world = true
	#Allows lost tablets to find modded structures [false/true|default:true]
	lost_tablet_modded_structure = true

#Allows to customize or disable the enchantments
[enchantments]
	#Maximum duration of stolen effects in minutes [1..MAX|default:1440]
	#Range: > 1
	max_duration_magic_siphon = 1440
	#The wearer is also affected by the effect if his alignment is not bad [false/true|default:true]
	nerf_plague_bringer = true
	#Duration of applied effects in seconds [1..MAX|default:10]
	#Range: > 1
	duration_plague_bringer = 10
	#Restricts the effect of Shadow Step to players [false/true|default:true]
	restrict_shadow_step_to_player = true

#Options related to the command recovery and auto-save of players
[recovery]
	#Enables to backup automatically players [false/true|default:true]
	recovery_player_enable = true
	#Enables to backup automatically dead familiars [false/true|default:true]
	recovery_familiar_enable = true
	#Time in minutes between players' backups [10..1000|default:40]
	#Range: 5 ~ 1000
	recovery_player_timer = 20
	#Backup players on death [false/true|default:false]
	backup_on_death = false
	#Maximum number of backups per player [5..100|default:15]
	#Range: 5 ~ 100
	recovery_player_max_saves = 15

#Allows to change the chance to drop some items
[loot]
	#Allows the undeads to have a low chance to drop their skull [false/true|default:true]
	undead_can_drop_skull = true
	#Chance on 1000 to receive a random scroll on undead boss [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_random_scroll_on_boss = 100
	#Chance on 1000 to receive a random poppet on undead boss [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_random_poppet_on_boss = 100
	#Chance on 1000 for undead mobs to drop Grave's Dust [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_grave_dust = 100
	#Chance on 1000 to receive a decorative grave on undead boss [0..1000|default:50]
	#Range: 0 ~ 1000
	chance_decorative_grave_on_boss = 30
	#Chance on 1000 to receive a Soul Receptacle on undead boss [0..1000|default:50]
	#Range: 0 ~ 1000
	chance_soul_receptacle_on_boss = 50
	#Defines the allowed loottables having a chance to contain a magic item from Tombstone
	treasure_loot_table = ["minecraft:chests/end_city_treasure", "minecraft:chests/abandoned_mineshaft", "minecraft:chests/nether_bridge", "minecraft:chests/stronghold_library", "minecraft:chests/desert_pyramid", "minecraft:chests/jungle_temple", "minecraft:chests/igloo_chest", "minecraft:chests/woodland_mansion"]

#Allows to enable some features related to others mods
[compatibility]
	#Keeps the cosmetic armor when you die [false/true|default:true]
	keep_cosmetic_armor = true
	#Disables to disenchant items from tetra mod [false/true|default:false]
	disable_disenchantment_for_tetra = false
	#Allows to auto-equip the slots from Curio mod [false/true|default:true]
	allow_curio_auto_equip = true

