
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 10333107

[exnihilosequentia]
	#Should gravel sieve recipes be added.
	sieveGravel = false
	#Should crushed netherrack sieve recipes be added.
	sieveCrushedNetherrack = false
	#Should crushed end stone sieve recipes be added.
	sieveCrushedEndstone = false

